### ISSUE TITLE
关于跨被试的模态消融实验

### ISSUE THREAD

**Issue by Huai-qIu-tec** [935963004/MAET#1]
很感谢贵团队在多模态情绪识别领域带来的精彩工作，MAET给我带来的受益良多，关于MAET的实验我有以下几个问题希望请教贵团队：

1. 文中展示了被试内的模态消融实验和对比实验，请问在跨被试训练中有做模态的消融实验吗？
2. 最近域对抗方法在情绪识别领域有很广泛的应用，但是在MAET中似乎对于结果的提升并不大，请问这是为何？

再次感谢吕老师团队带来的精彩工作！

**Comment by 935963004** [comment]
感谢关注我们的工作。以下是针对您的问题的答复，希望能帮助到您：
1)  我们并未在跨被试的实验中做模态的消融实验，跨被试训练仅使用了EEG。
2) 本文中域对抗方法提升不大可能是由于以下原因导致的：1）不同于现有的很多跨被试工作（如现有的大部分在SEED系列数据集上的工作，在留一交叉验证的实验设置下，实际上对于每个作为测试集的被试，在他们的每个session上单独调参获得结果，最终取所有session的准确率平均值汇报在论文中），在本文中，对于每个测试的被试，我们将被试的所有4个session被合并在一起作为测试集。这样的实验设置比已有的很多工作更为困难，将会导致准确率的下降；2）我们的实验基于域泛化的设置下，即我们无法获得目标域的任何数据，而很多情绪识别领域使用域对抗的工作基于域适应的设置下，即允许使用无标签的目标域数据。域泛化比域适应的设置更加困难，也更加接近实际情况，因此准确率也会不如域适应的方法，使得提升不明显；3）我们使用的域对抗方法相对较为基础，并未考虑使用更新、更高级的跨被试方法，这也可能是提升不明显的原因。我们希望我们的方法能够成为一个较好的baseline，更多研究者能够开发出更加有效的算法，提升跨被试的情绪识别性能。

以上。

**Comment by Huai-qIu-tec** [comment]
非常感谢您的详细回复，对于域对抗的解释给我带来了很多新的信息，再次非常感谢贵团队带来的精彩工作！
